[package]
name = "nodoxus"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/techton7/nodoxus"
authors = ["Techton <contact@techton.io>"]
description = "High-performance, reactive node graph and flow engine for Dioxus."
readme = "README.md"
keywords = ["dioxus", "graph", "flow", "canvas", "node-graph"]
categories = ["gui", "visualization"]

[dependencies]
dioxus = { version = "0.7.0", default-features = false, features = ["hooks", "signals", "macro", "html"] }

[dev-dependencies]
dioxus = { version = "0.7.0", default-features = false, features = ["minimal"] }
